language: ruby
services:
  - elasticsearch
before_script:
  - bundle exec rake db:setup
script:
  - bundle exec rspec
notifications:
  slack:
    secure: L7ysz/oWaFNMmSFmJN4z2iRqyDX2zmT8sqvsukKTNMyl9ENqbZFPyvC53ICMa2DLtP/X/XX1tzfHEqg9hZ2On2hju/Ohn9DG+RRjCm5Cu+05rpkliZO98gfVo1pTAfA4vn3HXsSHHRL5tmjUx7+YxbbF3YugJ2M0TUqFxI/1yiM=
