language: ruby
cache:
  directories:
    - ~/cache
services:
  - docker
before_install:
  - docker-compose --version
  - mv docker-compose.ci.yml docker-compose.override.yml
  - docker-compose pull
  - docker-compose run --rm --no-deps web bundle install
  - docker-compose up -d db elasticsearch
  - docker-compose run --rm --no-deps web rake db:setup
  - docker-compose run --rm --no-deps web rake db:test:prepare
script:
  - docker-compose run --rm web bundle exec rspec
notifications:
  slack:
    secure: L7ysz/oWaFNMmSFmJN4z2iRqyDX2zmT8sqvsukKTNMyl9ENqbZFPyvC53ICMa2DLtP/X/XX1tzfHEqg9hZ2On2hju/Ohn9DG+RRjCm5Cu+05rpkliZO98gfVo1pTAfA4vn3HXsSHHRL5tmjUx7+YxbbF3YugJ2M0TUqFxI/1yiM=


