development:
  adapter: mysql2
  encoding: utf8
  database: mbuilder_development
  pool: 5
  username: root
  password:

test:
  adapter: mysql2
  encoding: utf8
  database: mbuilder_test
  pool: 5
  username: root
  password:

production:
  adapter: mysql2
  encoding: utf8
  database: mbuilder
  pool: 5
  username: root
  password:
