development:
  url: http://nuntium.instedd.org
  account: instedd-stg
  application: mbuilder
  password: mbuilder
  incoming_username: mbuilder
  incoming_password: mbuilder

production:
  url: http://nuntium.instedd.org
  account: instedd-stg
  application: mbuilder
  password: mbuilder
  incoming_username: mbuilder
  incoming_password: mbuilder

test:
  url: http://nuntium.manas.com.ar
  account: manas
  application: mbuilder
  password: mbuilder
  incoming_username: mbuilder
  incoming_password: mbuilder
