name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2

      - name: Set environment up
        run: |
          docker-compose pull
          docker-compose build
          docker-compose run --rm web bundle install
          docker-compose run --rm web bundle exec irb -d debug-build.rb
          docker-compose run --rm web bundle exec rake db:setup
          docker-compose run --rm web bundle exec rake db:test:prepare

      - name: Run specs
        run: |
          docker-compose run --rm web bundle exec rspec

  build:
    needs: test
    runs-on: ubuntu-22.04
    env:
      DOCKER_REPOSITORY: 'instedd/mbuilder'
      DOCKER_USER: ${{ secrets.DOCKER_USER }}
      DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
    steps:
      - uses: actions/checkout@v2
      - name: Build image & push to Docker Hub
        run: ./build.sh
